### ISSUE TITLE
用PotPlayer打开，统统都是服务器已关闭或地址错误

### ISSUE THREAD

**Issue by ahdung** [hujingguang/ChinaIPTV#2]
![image](https://github.com/hujingguang/ChinaIPTV/assets/12094247/5fb82ff8-7219-4de2-a30b-da270ed2c49b)

**Comment by solarcellsky** [comment]
https://iina.io/ 这个试试。我试了基本都能看的。

**Comment by ahdung** [comment]
是我的问题，我的防火墙禁了potplayer。
